import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "AestheticBD  | Professionals @ Your Service ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {/* <div className="container mx-auto ">{children}</div> */}
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
